version: '3.7'

services:

  akaunting:
    container_name: akaunting
    build:
      dockerfile: fpm.Dockerfile
      context: .
    volumes:
      - akaunting-data:/var/www/html
    restart: unless-stopped
    env_file:
      - env/run.env
    environment:
      - AKAUNTING_SETUP
    depends_on:
      - akaunting-db

  akaunting-proxy:
    image: nginx:1.19.0
    ports:
      - 8080:80
    depends_on:
      - akaunting
    volumes:
      - akaunting-data:/var/www/html
      - ./nginx/templates:/etc/nginx/templates

  akaunting-db:
    container_name: akaunting-db
    image: mariadb
    volumes:
      - akaunting-db:/var/lib/mysql
    restart: unless-stopped
    env_file:
      - env/db.env

volumes:
  akaunting-data:
  akaunting-db:
